# Generated by Django 6.0.3 on 2026-03-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_borrowrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
